# Configuration for display settings
pygame_display:
  width: 1920  # Width of the display in pixels
  height: 1080 # Height of the display in pixels

# Configuration for simulated vehicles
simulated_vehicles:
  ego_vehicle: vehicle.tesla.model3
  smp: 10 # Number of smart vehicles spawned
  rvt: 30 # Number of random traffic vehicles spawned

# Configuration for Sensors
sensors:
  z: 1.6 # Sensor height on the vehicles
  camera_height: 300
  camera_width: 200
  camera_fov: 100